version: '3.1'
services:
  web:
    image: werp
    command: python3 odoo-bin -d odoo --db_user odoo --db_password odoo --limit-memory-hard 0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=odoo
  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo

# version: '3.1'
# services:
#   odoo:
#     image: werp
#     command: python3 odoo-bin -d odoo --db_user odoo --db_password odoo --limit-memory-hard 0
#     # command: ["odoo", "/usr/local/bin/wait-for-psql.py"]
#     links:
#       - db:db
#     depends_on:
#       - db
#     volumes:
#       - /var/run/postgresql:/var/run/postgresql
#     # environment:
#       # - PGHOST=database
#       # - PGUSER=odoo
#       # - PGPASSWORD=odoo
#     ports:
#       - 8069:8069
#   db:
#     image: postgres:13
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_HOST_AUTH_METHOD=trust
#       - POSTGRES_DB=odoo
#       - POSTGRES_PASSWORD=odoo
#       - POSTGRES_USER=odoo

# version: '3.3'
# services:
#   postgres:
#     image: postgres:9.5
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_USER=admin
#       - POSTGRES_PASSWORD=admin

#   odoo:
#     image: odoo-werp
#     command: python3 odoo/odoo-bin --limit-memory-hard 0
#     ports:
#       - 8069:8069
#     links:
#       - postgres:db
#     environment:
#       - ODOO_ADMIN_PASSWD=admin
#       - ODOO_DB_USER=admin
#       - ODOO_DB_PASSWORD=admin

