version: '3.1'
services:
  web:
    image: werp
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
# version: '3.3'
# services:
#   postgres:
#     image: postgres:9.5
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_USER=admin
#       - POSTGRES_PASSWORD=admin

#   odoo:
#     image: odoo-werp
#     command: python3 odoo/odoo-bin --limit-memory-hard 0
#     ports:
#       - 8069:8069
#     links:
#       - postgres:db
#     environment:
#       - ODOO_ADMIN_PASSWD=admin
#       - ODOO_DB_USER=admin
#       - ODOO_DB_PASSWORD=admin

