{
    'name': "Giao hàng nhanh",
    'summary': """Integration App In Odoo With Delivery In Company GHN""",
    # 'description': """ ghn API """,
    'author': "Magenest",
    'website': "http://magenest.com/",
    'sequence':'10',
    'images': ['static/description/ghn_background.png'],
    'category': 'Extra Tools',
    'version': '1.0',
    'depends': ['base','contacts', 'sale', 'delivery', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'data/ghn_cron_job.xml',
        'views/res_partner.xml',
        'views/delivery_carrier.xml',
        'views/res_company.xml',
        'views/sale_order_view.xml',
        'views/res_district_view.xml',
        'views/res_ward_view.xml',
        'views/stock_picking.xml',
        'views/res_config_settings_view.xml',
        'views/stock_warehouse.xml',
        'views/res_country_state.xml',
        'views/lunch_call_api.xml',
        'wizard/choose_delivery_carrier_view.xml',
        'data/res_district_demo.xml',
        'data/res_ward_demo.xml',
    ],
    # 'css': ['static/src/css/crm.css'],
    # 'js': ['static/src/js/patient_ajax_2.js'],
    'assets': {
        'web.report_assets_common': [
            'product/static/src/css/ticket.css',
        ],
    },
    'installable': True,
    'application': False, # application or technical module
    'auto_install': False,
    'license': 'OPL-1',
}